#!/usr/bin/env bash
# Canton MVP — Bootstrap local environment for Quickstart overlay mode
#
# Prerequisites:
#   - cn-quickstart cloned and built separately
#   - Docker running
#
# Usage:
#   ./integrations/quickstart-overlay/scripts/bootstrap.sh
#
# This script:
#   1. Validates Docker is available
#   2. Generates .env from port-map.json (if missing)
#   3. Validates required services (optional; requires Quickstart to be running)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OVERLAY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$OVERLAY_DIR/../.." && pwd)"

echo "[canton-mvp] Bootstrap Quickstart overlay environment"
echo "  Overlay dir: $OVERLAY_DIR"
echo "  Repo root:   $REPO_ROOT"
echo ""

# 1. Check Docker
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not available. Install Docker and ensure it is running."
  exit 1
fi
echo "[OK] Docker available"

# 2. Generate .env from port-map if missing
ENV_FILE="$REPO_ROOT/.env"
PORT_MAP="$OVERLAY_DIR/port-map.json"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[INFO] .env not found. Creating from port-map.json..."
  if [[ -f "$PORT_MAP" ]]; then
    # Extract env vars from port-map (simplified; use map-ports.sh for full generation)
    cat >> "$ENV_FILE" << 'EOF'
# Generated by integrations/quickstart-overlay/scripts/bootstrap.sh
LEDGER_API_URL=http://canton.localhost:3975
VALIDATOR_API_URL=http://canton.localhost:3903
SCAN_API_URL=http://scan.localhost:4000
PORT=8080
AUTH_MODE=shared-secret
EOF
    echo "[OK] Created .env"
  else
    echo "[WARN] port-map.json not found. Create .env manually from .env.example"
  fi
else
  echo "[OK] .env exists"
fi

# 3. Optional: validate services (requires Quickstart to be running)
echo ""
echo "Next steps:"
echo "  1. Start cn-quickstart LocalNet: cd cn-quickstart/quickstart && make start"
echo "  2. Run: $OVERLAY_DIR/scripts/validate-services.sh"
echo "  3. Run: pnpm dev"
echo ""
echo "Bootstrap complete."
