#!/usr/bin/env bash
# Canton MVP — Map Quickstart ports to canton-mvp .env
#
# Reads port-map.json and outputs env vars for the default participant.
# Usage:
#   ./integrations/quickstart-overlay/scripts/map-ports.sh
#   ./integrations/quickstart-overlay/scripts/map-ports.sh > .env.quickstart
#
# Requires: jq (https://stedolan.github.io/jq/)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OVERLAY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PORT_MAP="$OVERLAY_DIR/port-map.json"

if [[ ! -f "$PORT_MAP" ]]; then
  echo "ERROR: port-map.json not found at $PORT_MAP" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required. Install from https://stedolan.github.io/jq/" >&2
  exit 1
fi

echo "# Generated by map-ports.sh from port-map.json"
echo "# Participant: $(jq -r '.defaultParticipant' "$PORT_MAP")"
echo ""

jq -r '.envMapping | to_entries[] | "\(.key)=\(.value)"' "$PORT_MAP"

echo ""
echo "PORT=8080"
echo "AUTH_MODE=shared-secret"
